"use client"

import type React from "react"
import { createContext, useContext, useState } from "react"

type Language = "en" | "zh" | "yue" | "fr"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, options?: Record<string, any>) => string
  getLanguageName: (lang: Language) => string
  getSpeechLanguage: (lang: Language) => string
}

const translations = {
  en: {
    // Language names
    "language.english": "English",
    "language.chinese": "中文",
    "language.cantonese": "廣東話",
    "language.french": "Français",

    // Audio instructions
    "audio.instruction": "🔊 Audio Instruction",
    "audio.instruction_playing": "🔊 Playing...",
    "audio.instruction_error": "Audio instruction not available",
    "audio.error_playing": "Error playing audio. Please try again.",
    "audio.not_supported": "Speech synthesis not supported in this browser.",

    // Registration & Login
    "register.title": "Register with Phone Number",
    phone: "Phone Number",
    "register.submit": "Register",
    "register.error.invalid": "Please enter a valid phone number",
    "register.error.exists": "Phone number already registered",
    "login.title": "Login with Phone Number",
    "login.submit": "Login",
    "login.error.notfound": "Phone number not found",
    "login.admin": "Admin Login",
    "login.enter_phone": "Enter your registered phone number to continue",
    "login.new_user": "New User? Register Here",
    "login.already_account": "Already have an account? Login here",
    "registration.description": "Enter your phone number to begin the mental health assessment",
    "dummy_pin.label": "Dummy PIN",
    "dummy_pin.placeholder.login": "Enter Dummy PIN",
    "dummy_pin.placeholder.register": "Create Dummy PIN",

    // Dashboard
    "dashboard.title": "Mental Health Assessment Dashboard",
    "dashboard.moca": "Montreal Cognitive Assessment (MoCA)",
    "dashboard.moca.description": "Montreal Cognitive Assessment - 30 points total",
    "dashboard.mmse": "Mini-Mental State Examination (MMSE)",
    "dashboard.mmse.description": "Mini-Mental State Examination - 30 points total",
    "dashboard.upload": "Chinese Traditional Medicine (TCM) Image Upload",
    "dashboard.upload.description": "Upload medical images and documents",
    "dashboard.completed": "Completed",
    "dashboard.pending": "Pending",
    "dashboard.resume": "Resume Assessment",
    "dashboard.view_results": "View Results",
    "dashboard.retake": "Retake",
    "dashboard.confirm_retake": "Confirm Retake",
    "dashboard.score": "Score",
    "dashboard.results_final": "Assessment completed. Results are final.",
    "dashboard.manage_files": "Manage Files",
    "dashboard.upload_files": "Upload Files",
    "dashboard.files_uploaded": "Files uploaded: {count}",
    "dashboard.phone": "Phone",
    "dashboard.logout": "Logout",

    // MoCA
    "moca.title": "Montreal Cognitive Assessment",
    "moca.visuospatial": "Visuospatial Skills - Clock Drawing",
    "moca.visuospatial.instruction": "Drag the clock hands to show the time: 10 after 2 (2:10)",
    "moca.executive": "Executive Function - Trail Making",
    "moca.executive.instruction":
      "Connect the circles in alternating order: 1-A-2-B-3-C-4-D. Circles 1, A, and 2 are pre-connected.",
    "moca.naming": "Naming Animals",
    "moca.naming.instruction": "Look at each image and type the name of the animal you see.",
    "moca.memory": "Memory Tasks",
    "moca.memory.instruction": "You will be shown {count} words one by one. Remember them for later recall.",
    "moca.attention": "Attention Tasks",
    "moca.attention.instruction": "Look carefully at the image and count the number of dogs you can see.",
    "moca.language": "Language & Abstraction",
    "moca.language.instruction": "Listen carefully and complete the tasks.",
    "moca.orientation": "Orientation",
    "moca.orientation.instruction": "Please answer the following questions about the current date and location.",

    // MMSE
    "mmse.title": "Mini-Mental State Examination",
    "mmse.orientation": "Orientation",
    "mmse.orientation.instruction": "Please answer the following questions about time and place.",
    "mmse.registration": "Registration & Recall",
    "mmse.attention": "Attention & Calculation",
    "mmse.naming": "Naming Objects",
    "mmse.naming.instruction": "Look at each image and type the name of the object you see.",
    "mmse.repetition": "Repetition",
    "mmse.repetition.instruction": "Listen carefully to the sentence and type exactly what you hear.",
    "mmse.writing": "Writing",
    "mmse.writing.instruction":
      "Please write a complete sentence. The sentence should have a subject and a verb and make sense.",
    "mmse.copying": "Copying Design",
    "mmse.copying.instruction": "Look at the shape below and answer the question about it.",

    // Questions
    "question.date": "What is today's date?",
    "question.month": "What is the current month?",
    "question.year": "What is the current year?",
    "question.day": "What day of the week is it?",
    "question.country": "What country are we in?",
    "question.season": "What season is it?",
    "question.president": "Who is the current president?",
    "question.sea": "Name a sea:",
    "question.similarity": "In what way are a train and a bicycle alike?",
    "question.dogs": "How many dogs do you see?",
    "question.angles": "How many angles does this shape have?",
    "question.subtract": "What is 10 minus 7?",
    "question.add": "What should we add to 4 to get 7?",
    "question.your_answer": "Your answer:",
    "question.type_sentence": "Type the sentence you heard:",
    "question.write_sentence": "Write your sentence here:",
    "question.animal_label": "Animal {index}:",
    "question.object_label": "Object {index}:",

    // Audio sentences
    "audio.moca_sentence_en_path": "/audio/moca_sentence_en.mp3",
    "audio.moca_sentence_zh_path": "/audio/moca_sentence_zh.mp3",
    "audio.mmse_sentence_en_path": "/audio/mmse_sentence_en.mp3",
    "audio.mmse_sentence_zh_path": "/audio/mmse_sentence_zh.mp3",
    "audio.play": "Play Audio",
    "audio.playing": "Playing...",
    "audio.played_success": "✓ Audio played. Now type what you heard below.",

    // Memory words
    "memory.moca.words": ["Face", "Velvet", "Church", "Daisy", "Red"],
    "memory.mmse.words": ["Apple", "Table", "Penny"],
    "memory.get_ready": "Get ready! Words will appear in {countdown} seconds...",
    "memory.word_of": "Word {current} of {total}",
    "memory.preparing_recall": "Preparing recall phase...",
    "memory.recall_instruction": "Please type the {count} words you just saw, in any order.",
    "memory.submit_recall": "Submit Recall",

    // Upload
    "upload.instruction": "Upload your medical images and documents. Supported formats: PNG, JPEG, PDF (max 10MB each)",
    "upload.drag_drop": "Drop files here or click to browse",
    "upload.file_types": "PNG, JPEG, PDF files up to 10MB each",
    "upload.error.invalid_file_type_size": "Please select valid files (PNG, JPEG, PDF) under 10MB",
    "upload.error.failed": "Upload failed",
    "upload.error.remove_failed": "Failed to remove file",
    "upload.uploading": "Uploading files...",
    "upload.uploaded_files": "Uploaded Files ({count})",
    "upload.complete_section": "Complete Upload Section",
    "upload.using_uploaded_images": "Using your uploaded images for this task.",

    // Results Display
    "results.title": "{assessmentType} Assessment Results",
    "results.score_percentage": "{percentage}% Score",
    "results.section_breakdown": "Section Breakdown",
    "results.points": "{score} points",
    "results.back_to_dashboard": "Back to Dashboard",
    "results.interpretation.normal": "Normal",
    "results.interpretation.mild_impairment": "Mild Cognitive Impairment",
    "results.interpretation.possible_decline": "Possible Cognitive Decline",
    "results.interpretation.severe_impairment": "Severe Cognitive Impairment",
    "results.moca.normal_range": "26-30: Normal cognition",
    "results.moca.mild_range": "18-25: Mild cognitive impairment",
    "results.moca.decline_range": "<18: Possible cognitive decline",
    "results.mmse.normal_range": "21-28: Normal cognition",
    "results.mmse.mild_range": "15-20: Mild cognitive impairment",
    "results.mmse.severe_range": "<14: Severe cognitive impairment",

    // Admin Panel
    "admin.title": "Admin Dashboard",
    "admin.login_title": "Admin Login",
    "admin.username": "Username",
    "admin.password": "Password",
    "admin.login_button": "Login",
    "admin.view_assessments": "View Assessments",
    "admin.view_files": "View Files",
    "admin.export_csv": "Export CSV",
    "admin.total_users": "Total Users",
    "admin.completed_assessments": "Completed Assessments",
    "admin.avg_moca_score": "Avg MoCA Score",
    "admin.uploaded_files": "Uploaded Files",
    "admin.registered": "Registered",
    "admin.assessments_count": "{count} assessments",
    "admin.files_count": "{count} files",
    "admin.completed_count": "{count} completed",
    "admin.in_progress_count": "{count} in progress",
    "admin.select_user": "Select a user to view their details",
    "admin.user_files": "User Files",
    "admin.assessment_details": "Assessment Details",
    "admin.no_files_uploaded": "No files uploaded by this user",
    "admin.no_completed_assessments": "No completed assessments by this user",
    "admin.no_progress_assessments": "No assessments in progress for this user",
    "admin.last_updated": "Last Updated",
    "admin.current_step": "Current Step",
    "admin.scores_so_far": "Scores so far",
    "admin.total_score": "Total Score",
    "admin.section_scores": "Section Scores",
    "admin.laboratory_analysis": "Laboratory Analysis:",
    "admin.enter_analysis": "Enter laboratory analysis...",
    "admin.update_analysis": "Update Analysis",
    "admin.registered_users": "Registered Users",
    "admin.assessments_in_progress": "Assessments in Progress",
    "admin.avg_scores_title": "Average Assessment Scores",
    "admin.score_distribution_title": "Score Distribution",
    "admin.progress_trend_title": "Assessment Progress Trends Over Time",
    "admin.select_user_filter": "Select User",
    "admin.all_users": "All Users",
    "admin.select_assessment_type": "Select Assessment Type",
    "admin.all_assessments": "All Assessments",

    // Theme
    "theme.light": "Light Mode",
    "theme.dark": "Dark Mode",
    "theme.system": "System",

    // Common
    "common.assessment": "Assessment",
    "common.step": "Step",
    "common.of": "of",
    "common.progress": "Progress",
    "common.next": "Next",
    "common.submit": "Submit",
    "common.back": "Back",
    "common.score": "Score",
    "common.total": "Total",
    "common.loading": "Loading...",
    "common.login": "Login",
    "common.logout": "Logout",
    "common.resume": "Resume",
    "common.start": "Start Assessment",
    "common.view_results": "View Results",
    "common.retake": "Retake",
    "common.confirm_retake": "Confirm Retake",
    "common.skip_task": "Skip Task",
    "common.animal": "Animal",
    "common.object": "Object",
    "common.television": "television",
    "common.tiger": "tiger",
    "common.rhinoceros": "rhinoceros",
    "common.camel": "camel",
    "common.house": "house",
    "common.bag": "bag",
    "common.walk": "walk",
    "common.run": "run",
    "common.wheel": "wheel",
    "common.jump": "jump",
    "common.word": "Word",
    "common.president_name": "xi jinping",
    "common.china": "china",
    "common.spring": "spring",
    "common.summer": "summer",
    "common.autumn": "autumn",
    "common.winter": "winter",
    "common.month_1": "January",
    "common.month_2": "February",
    "common.month_3": "March",
    "common.month_4": "April",
    "common.month_5": "May",
    "common.month_6": "June",
    "common.month_7": "July",
    "common.month_8": "August",
    "common.month_9": "September",
    "common.month_10": "October",
    "common.month_11": "November",
    "common.month_12": "December",
    "common.day_sunday": "sunday",
    "common.day_monday": "monday",
    "common.day_tuesday": "tuesday",
    "common.day_wednesday": "wednesday",
    "common.day_thursday": "thursday",
    "common.day_friday": "friday",
    "common.day_saturday": "saturday",
  },
  zh: {
    // Language names
    "language.english": "English",
    "language.chinese": "中文",
    "language.cantonese": "廣東話",
    "language.french": "Français",

    // Audio instructions
    "audio.instruction": "🔊 音频指导",
    "audio.instruction_playing": "🔊 播放中...",
    "audio.instruction_error": "音频指导不可用",
    "audio.error_playing": "播放音频时出错。请重试。",
    "audio.not_supported": "此浏览器不支持语音合成。",

    // Registration & Login
    "register.title": "手机号码注册",
    phone: "手机号码",
    "register.submit": "注册",
    "register.error.invalid": "请输入有效的手机号码",
    "register.error.exists": "手机号码已注册",
    "login.title": "手机号码登录",
    "login.submit": "登录",
    "login.error.notfound": "手机号码未找到",
    "login.admin": "管理员登录",
    "login.enter_phone": "输入您注册的手机号码以继续",
    "login.new_user": "新用户？点击注册",
    "login.already_account": "已有账户？点击登录",
    "registration.description": "输入您的手机号码以开始心理健康评估",
    "dummy_pin.label": "虚拟密码",
    "dummy_pin.placeholder.login": "输入虚拟密码",
    "dummy_pin.placeholder.register": "创建虚拟密码",

    // Dashboard
    "dashboard.title": "心理健康评估仪表板",
    "dashboard.moca": "蒙特利尔认知评估 (MoCA)",
    "dashboard.moca.description": "蒙特利尔认知评估 - 总分30分",
    "dashboard.mmse": "简易精神状态检查 (MMSE)",
    "dashboard.mmse.description": "简易精神状态检查 - 总分30分",
    "dashboard.upload": "中医药图像上传",
    "dashboard.upload.description": "上传医疗图像和文件",
    "dashboard.completed": "已完成",
    "dashboard.pending": "待完成",
    "dashboard.resume": "继续评估",
    "dashboard.view_results": "查看结果",
    "dashboard.retake": "重拍",
    "dashboard.confirm_retake": "确认重考",
    "dashboard.score": "得分",
    "dashboard.results_final": "评估已完成。结果为最终结果。",
    "dashboard.manage_files": "管理文件",
    "dashboard.upload_files": "上传文件",
    "dashboard.files_uploaded": "已上传文件：{count}",
    "dashboard.phone": "电话",
    "dashboard.logout": "登出",

    // MoCA
    "moca.title": "蒙特利尔认知评估",
    "moca.visuospatial": "视觉空间技能 - 时钟绘制",
    "moca.visuospatial.instruction": "拖动时钟指针显示时间：2点10分",
    "moca.executive": "执行功能 - 连线测试",
    "moca.executive.instruction": "按交替顺序连接圆圈：1-A-2-B-3-C-4-D。圆圈1、A和2已经预连接。",
    "moca.naming": "动物命名",
    "moca.naming.instruction": "看每张图片并输入您看到的动物名称。",
    "moca.memory": "记忆任务",
    "moca.memory.instruction": "您将看到{count}个单词逐一显示。请记住它们以便稍后回忆。",
    "moca.attention": "注意力任务",
    "moca.attention.instruction": "仔细观察图像并数出您能看到的狗的数量。",
    "moca.language": "语言与抽象",
    "moca.language.instruction": "仔细听并完成任务。",
    "moca.orientation": "定向力",
    "moca.orientation.instruction": "请回答以下关于当前日期和地点的问题。",

    // MMSE
    "mmse.title": "简易精神状态检查",
    "mmse.orientation": "定向力",
    "mmse.orientation.instruction": "请回答以下关于时间和地点的问题。",
    "mmse.registration": "注册与回忆",
    "mmse.attention": "注意力与计算",
    "mmse.naming": "物体命名",
    "mmse.naming.instruction": "看每张图片并输入您看到的物体名称。",
    "mmse.repetition": "重复",
    "mmse.repetition.instruction": "仔细听句子并准确输入您听到的内容。",
    "mmse.writing": "书写",
    "mmse.writing.instruction": "请写一个完整的句子。句子应该有主语和谓语并且有意义。",
    "mmse.copying": "复制设计",
    "mmse.copying.instruction": "看下面的形状并回答有关它的问题。",

    // Questions
    "question.date": "今天是几号？",
    "question.month": "现在是几月？",
    "question.year": "现在是哪一年？",
    "question.day": "今天是星期几？",
    "question.country": "我们在哪个国家？",
    "question.season": "现在是什么季节？",
    "question.president": "现任主席是谁？",
    "question.sea": "说出一个海的名字：",
    "question.similarity": "火车和自行车有什么相似之处？",
    "question.dogs": "您看到多少只狗？",
    "question.angles": "这个形状有多少个角？",
    "question.subtract": "10减7等于多少？",
    "question.add": "4加多少等于7？",
    "question.your_answer": "您的答案：",
    "question.type_sentence": "输入您听到的句子：",
    "question.write_sentence": "在此处写下您的句子：",
    "question.animal_label": "动物 {index}：",
    "question.object_label": "物体 {index}：",

    // Audio sentences
    "audio.moca_sentence_en_path": "/audio/moca_sentence_en.mp3",
    "audio.moca_sentence_zh_path": "/audio/moca_sentence_zh.mp3",
    "audio.mmse_sentence_en_path": "/audio/mmse_sentence_en.mp3",
    "audio.mmse_sentence_zh_path": "/audio/mmse_sentence_zh.mp3",
    "audio.play": "播放音频",
    "audio.playing": "正在播放...",
    "audio.played_success": "✓ 音频已播放。现在在下方输入您听到的内容。",
    "audio.error_playing": "播放音频时出错。请重试。",

    // Memory words
    "memory.moca.words": ["脸", "天鹅绒", "教堂", "雏菊", "红色"],
    "memory.mmse.words": ["苹果", "桌子", "硬币"],
    "memory.get_ready": "准备好了！单词将在 {countdown} 秒后出现...",
    "memory.word_of": "第 {current} 个词，共 {total} 个",
    "memory.preparing_recall": "正在准备回忆阶段...",
    "memory.recall_instruction": "请按任意顺序输入您刚才看到的 {count} 个单词。",
    "memory.submit_recall": "提交回忆",

    // Upload
    "upload.instruction": "上传您的医疗图像和文件。支持格式：PNG、JPEG、PDF（每个最大10MB）",
    "upload.drag_drop": "将文件拖放到此处或点击浏览",
    "upload.file_types": "PNG、JPEG、PDF文件，每个最大10MB",
    "upload.error.invalid_file_type_size": "请选择有效文件（PNG、JPEG、PDF），大小在10MB以下",
    "upload.error.failed": "上传失败",
    "upload.error.remove_failed": "删除文件失败",
    "upload.uploading": "正在上传文件...",
    "upload.uploaded_files": "已上传文件 ({count})",
    "upload.complete_section": "完成上传部分",
    "upload.using_uploaded_images": "正在使用您上传的图片进行此任务。",

    // Results Display
    "results.title": "{assessmentType} 评估结果",
    "results.score_percentage": "{percentage}% 得分",
    "results.section_breakdown": "部分细分",
    "results.points": "{score} 分",
    "results.back_to_dashboard": "返回仪表板",
    "results.interpretation.normal": "正常",
    "results.interpretation.mild_impairment": "轻度认知障碍",
    "results.interpretation.possible_decline": "可能认知能力下��",
    "results.interpretation.severe_impairment": "重度认知障碍",
    "results.moca.normal_range": "26-30：正常认知",
    "results.moca.mild_range": "18-25：轻度认知障碍",
    "results.moca.decline_range": "<18：可能认知能力下降",
    "results.mmse.normal_range": "21-28：正常认知",
    "results.mmse.mild_range": "15-20：轻度认知障碍",
    "results.mmse.severe_range": "<14：重度认知障碍",

    // Admin Panel
    "admin.title": "管理员仪表板",
    "admin.login_title": "管理员登录",
    "admin.username": "用户名",
    "admin.password": "密码",
    "admin.login_button": "登录",
    "admin.view_assessments": "查看评估",
    "admin.view_files": "查看文件",
    "admin.export_csv": "导出CSV",
    "admin.total_users": "总用户数",
    "admin.completed_assessments": "已完成评估",
    "admin.avg_moca_score": "MoCA平均分",
    "admin.uploaded_files": "已上传文件",
    "admin.registered": "注册时间",
    "admin.assessments_count": "{count} 份评估",
    "admin.files_count": "{count} 个文件",
    "admin.completed_count": "{count} 已完成",
    "admin.in_progress_count": "{count} 进行中",
    "admin.select_user": "选择用户查看详情",
    "admin.user_files": "用户文件",
    "admin.assessment_details": "评估详情",
    "admin.no_files_uploaded": "该用户未上传任何文件",
    "admin.no_completed_assessments": "该用户未完成任何评估",
    "admin.no_progress_assessments": "该用户没有进行中的评估",
    "admin.last_updated": "最后更新",
    "admin.current_step": "当前步骤",
    "admin.scores_so_far": "目前得分",
    "admin.total_score": "总分",
    "admin.section_scores": "部分得分",
    "admin.laboratory_analysis": "实验室分析：",
    "admin.enter_analysis": "输入实验室分析...",
    "admin.update_analysis": "更新分析",
    "admin.registered_users": "註冊使用者",
    "admin.assessments_in_progress": "評估中",
    "admin.avg_scores_title": "平均评估分数",
    "admin.score_distribution_title": "分数分布",
    "admin.progress_trend_title": "评估进度随时间变化的趋势",
    "admin.select_user_filter": "选择用户",
    "admin.all_users": "所有用户",
    "admin.select_assessment_type": "选择评估类型",
    "admin.all_assessments": "所有评估",

    // Theme
    "theme.light": "浅色模式",
    "theme.dark": "深色模式",
    "theme.system": "系统",

    // Common
    "common.assessment": "评估",
    "common.step": "步骤",
    "common.of": "共",
    "common.progress": "进度",
    "common.next": "下一步",
    "common.submit": "提交",
    "common.back": "返回",
    "common.score": "得分",
    "common.total": "总分",
    "common.loading": "加载中...",
    "common.login": "登录",
    "common.logout": "登出",
    "common.resume": "继续",
    "common.start": "开始评估",
    "common.view_results": "查看结果",
    "common.retake": "重拍",
    "common.confirm_retake": "确认重考",
    "common.skip_task": "跳过任务",
    "common.animal": "动物",
    "common.object": "物体",
    "common.television": "电视",
    "common.tiger": "老虎",
    "common.rhinoceros": "犀牛",
    "common.camel": "骆驼",
    "common.house": "房子",
    "common.bag": "包",
    "common.walk": "走",
    "common.run": "跑",
    "common.wheel": "轮子",
    "common.jump": "跳",
    "common.word": "词",
    "common.president_name": "习近平",
    "common.china": "中国",
    "common.spring": "春天",
    "common.summer": "夏天",
    "common.autumn": "秋天",
    "common.winter": "冬天",
    "common.month_1": "一月",
    "common.month_2": "二月",
    "common.month_3": "三月",
    "common.month_4": "四月",
    "common.month_5": "五月",
    "common.month_6": "六月",
    "common.month_7": "七月",
    "common.month_8": "八月",
    "common.month_9": "九月",
    "common.month_10": "十月",
    "common.month_11": "十一月",
    "common.month_12": "十二月",
    "common.day_sunday": "星期日",
    "common.day_monday": "星期一",
    "common.day_tuesday": "星期二",
    "common.day_wednesday": "星期三",
    "common.day_thursday": "星期四",
    "common.day_friday": "星期五",
    "common.day_saturday": "星期六",
  },
  yue: {
    // Language names
    "language.english": "English",
    "language.chinese": "中文",
    "language.cantonese": "廣東話",
    "language.french": "Français",

    // Audio instructions
    "audio.instruction": "🔊 語音指導",
    "audio.instruction_playing": "🔊 播放緊...",
    "audio.instruction_error": "語音指導唔可用",
    "audio.error_playing": "播放音頻時出錯。請重試。",
    "audio.not_supported": "呢個瀏覽器唔支援語音合成。",

    // Registration & Login
    "register.title": "用電話號碼註冊",
    phone: "電話號碼",
    "register.submit": "註冊",
    "register.error.invalid": "請輸入有效嘅電話號碼",
    "register.error.exists": "電話號碼已經註冊咗",
    "login.title": "用電話號碼登入",
    "login.submit": "登入",
    "login.error.notfound": "搵唔到電話號碼",
    "login.admin": "管理員登入",
    "login.enter_phone": "輸入你註冊嘅電話號碼繼續",
    "login.new_user": "新用戶？去註冊",
    "login.already_account": "已經有戶口？去登入",
    "registration.description": "輸入你嘅電話號碼開始心理健康評估",
    "dummy_pin.label": "虛擬密碼",
    "dummy_pin.placeholder.login": "輸入虛擬密碼",
    "dummy_pin.placeholder.register": "創建虛擬密碼",

    // Dashboard
    "dashboard.title": "心理健康評估儀表板",
    "dashboard.moca": "蒙特利爾認知評估 (MoCA)",
    "dashboard.moca.description": "蒙特利爾認知評估 - 總分30分",
    "dashboard.mmse": "簡易精神狀態檢查 (MMSE)",
    "dashboard.mmse.description": "簡易精神狀態檢查 - 總分30分",
    "dashboard.upload": "中醫藥圖像上傳",
    "dashboard.upload.description": "上傳醫療圖像同文件",
    "dashboard.completed": "已完成",
    "dashboard.pending": "待完成",
    "dashboard.resume": "繼續評估",
    "dashboard.view_results": "查看結果",
    "dashboard.retake": "奪回",
    "dashboard.confirm_retake": "確認重考",
    "dashboard.score": "得分",
    "dashboard.results_final": "評估已完成。結果係最終結果。",
    "dashboard.manage_files": "管理文件",
    "dashboard.upload_files": "上傳文件",
    "dashboard.files_uploaded": "已上傳文件：{count}",
    "dashboard.phone": "電話",
    "dashboard.logout": "登出",

    // MoCA
    "moca.title": "蒙特利爾認知評估",
    "moca.visuospatial": "視覺空間技能 - 時鐘繪製",
    "moca.visuospatial.instruction": "拖動時鐘指針顯示時間：2點10分",
    "moca.executive": "執行功能 - 連線測試",
    "moca.executive.instruction": "按交替順序連接圓圈：1-A-2-B-3-C-4-D。圓圈1、A同2已經預先連接。",
    "moca.naming": "動物命名",
    "moca.naming.instruction": "睇每張圖片並輸入你睇到嘅動物名稱。",
    "moca.memory": "記憶任務",
    "moca.memory.instruction": "你會睇到{count}個單詞逐一顯示。請記住佢哋以便稍後回憶。",
    "moca.attention": "注意力任務",
    "moca.attention.instruction": "仔細觀察圖像並數出你能夠睇到嘅狗嘅數量。",
    "moca.language": "語言與抽象",
    "moca.language.instruction": "仔細聽並完成任務。",
    "moca.orientation": "定向力",
    "moca.orientation.instruction": "請回答以下關於當前日期同地點嘅問題。",

    // MMSE
    "mmse.title": "簡易精神狀態檢查",
    "mmse.orientation": "定向力",
    "mmse.orientation.instruction": "請回答以下關於時間同地點嘅問題。",
    "mmse.registration": "註冊與回憶",
    "mmse.attention": "注意力與計算",
    "mmse.naming": "物體命名",
    "mmse.naming.instruction": "睇每張圖片並輸入你睇到嘅物體名稱。",
    "mmse.repetition": "重複",
    "mmse.repetition.instruction": "仔細聽句子並準確輸入你聽到嘅內容。",
    "mmse.writing": "書寫",
    "mmse.writing.instruction": "請寫一個完整嘅句子。句子應該有主語同謂語並且有意義。",
    "mmse.copying": "複製設計",
    "mmse.copying.instruction": "睇下面嘅形狀並回答有關佢嘅問題。",

    // Questions
    "question.date": "今日係幾號？",
    "question.month": "而家係幾月？",
    "question.year": "而家係邊一年？",
    "question.day": "今日係星期幾？",
    "question.country": "我哋係邊個國家？",
    "question.season": "而家係咩季節？",
    "question.president": "現任主席係邊個？",
    "question.sea": "講出一個海嘅名：",
    "question.similarity": "火車同單車有咩相似之處？",
    "question.dogs": "你睇到幾多隻狗？",
    "question.angles": "呢個形狀有幾多個角？",
    "question.subtract": "10減7等於幾多？",
    "question.add": "4加幾多等於7？",
    "question.your_answer": "你嘅答案：",
    "question.type_sentence": "輸入你聽到嘅句子：",
    "question.write_sentence": "喺呢度寫低你嘅句子：",
    "question.animal_label": "動物 {index}：",
    "question.object_label": "物體 {index}：",

    // Audio sentences
    "audio.moca_sentence_en_path": "/audio/moca_sentence_en.mp3",
    "audio.moca_sentence_zh_path": "/audio/moca_sentence_zh.mp3",
    "audio.mmse_sentence_en_path": "/audio/mmse_sentence_en.mp3",
    "audio.mmse_sentence_zh_path": "/audio/mmse_sentence_zh.mp3",
    "audio.play": "播放音頻",
    "audio.playing": "播放緊...",
    "audio.played_success": "✓ 音頻已播放。而家喺下面輸入你聽到嘅內容。",
    "audio.error_playing": "播放音頻時出錯。請重試。",

    // Memory words
    "memory.moca.words": ["面", "絲絨", "教堂", "雛菊", "紅色"],
    "memory.mmse.words": ["蘋果", "檯", "硬幣"],
    "memory.get_ready": "準備好！單詞會喺 {countdown} 秒後出現...",
    "memory.word_of": "第 {current} 個詞，共 {total} 個",
    "memory.preparing_recall": "準備緊回憶階段...",
    "memory.recall_instruction": "請按任意順序輸入你啱啱睇到嘅 {count} 個單詞。",
    "memory.submit_recall": "提交回憶",

    // Upload
    "upload.instruction": "上傳你嘅醫療圖像同文件。支援格式：PNG、JPEG、PDF（每個最大10MB）",
    "upload.drag_drop": "將文件拖放到呢度或者點擊瀏覽",
    "upload.file_types": "PNG、JPEG、PDF文件，每個最大10MB",
    "upload.error.invalid_file_type_size": "請選擇有效文件（PNG、JPEG、PDF），大小喺10MB以下",
    "upload.error.failed": "上傳失敗",
    "upload.error.remove_failed": "刪除文件失敗",
    "upload.uploading": "上傳緊文件...",
    "upload.uploaded_files": "已上傳文件 ({count})",
    "upload.complete_section": "完成上傳部分",
    "upload.using_uploaded_images": "用緊你上傳嘅圖片進行呢個任務。",

    // Results Display
    "results.title": "{assessmentType} 評估結果",
    "results.score_percentage": "{percentage}% 得分",
    "results.section_breakdown": "部分細分",
    "results.points": "{score} 分",
    "results.back_to_dashboard": "返回儀表板",
    "results.interpretation.normal": "正常",
    "results.interpretation.mild_impairment": "輕度認知障礙",
    "results.interpretation.possible_decline": "可能認知能力下降",
    "results.interpretation.severe_impairment": "重度認知障礙",
    "results.moca.normal_range": "26-30：正常認知",
    "results.moca.mild_range": "18-25：輕度認知障礙",
    "results.moca.decline_range": "<18：可能認知能力下降",
    "results.mmse.normal_range": "21-28：正常認知",
    "results.mmse.mild_range": "15-20：輕度認知障礙",
    "results.mmse.severe_range": "<14：重度認知障礙",

    // Admin Panel
    "admin.title": "管理員儀表板",
    "admin.login_title": "管理員登入",
    "admin.username": "用戶名",
    "admin.password": "密碼",
    "admin.login_button": "登入",
    "admin.view_assessments": "查看評估",
    "admin.view_files": "查看文件",
    "admin.export_csv": "導出CSV",
    "admin.total_users": "總用戶數",
    "admin.completed_assessments": "已完成評估",
    "admin.avg_moca_score": "MoCA平均分",
    "admin.uploaded_files": "已上傳文件",
    "admin.registered": "註冊時間",
    "admin.assessments_count": "{count} 份評估",
    "admin.files_count": "{count} 個文件",
    "admin.completed_count": "{count} 已完成",
    "admin.in_progress_count": "{count} 進行中",
    "admin.select_user": "選擇用戶查看詳情",
    "admin.user_files": "用戶文件",
    "admin.assessment_details": "評估詳情",
    "admin.no_files_uploaded": "呢個用戶未上傳任何文件",
    "admin.no_completed_assessments": "呢個用戶未完成任何評估",
    "admin.no_progress_assessments": "呢個用戶冇進行中嘅評估",
    "admin.last_updated": "最後更新",
    "admin.current_step": "當前步驟",
    "admin.scores_so_far": "目前得分",
    "admin.total_score": "總分",
    "admin.section_scores": "部分得分",
    "admin.laboratory_analysis": "實驗室分析：",
    "admin.enter_analysis": "輸入實驗室分析...",
    "admin.update_analysis": "更新分析",
    "admin.registered_users": "註冊用戶",
    "admin.assessments_in_progress": "評估中",
    "admin.avg_scores_title": "平均評估分數",
    "admin.score_distribution_title": "分數分佈",
    "admin.progress_trend_title": "評估進度隨時間變化嘅趨勢",
    "admin.select_user_filter": "選擇用戶",
    "admin.all_users": "所有用戶",
    "admin.select_assessment_type": "選擇評估類型",
    "admin.all_assessments": "所有評估",

    // Theme
    "theme.light": "淺色模式",
    "theme.dark": "深色模式",
    "theme.system": "系統",

    // Common
    "common.assessment": "評估",
    "common.step": "步驟",
    "common.of": "共",
    "common.progress": "進度",
    "common.next": "下一步",
    "common.submit": "提交",
    "common.back": "返回",
    "common.score": "得分",
    "common.total": "總分",
    "common.loading": "載入中...",
    "common.login": "登入",
    "common.logout": "登出",
    "common.resume": "繼續",
    "common.start": "開始評估",
    "common.view_results": "查看結果",
    "common.retake": "奪回",
    "common.confirm_retake": "確認重考",
    "common.skip_task": "跳過任務",
    "common.animal": "動物",
    "common.object": "物體",
    "common.television": "電視",
    "common.tiger": "老虎",
    "common.rhinoceros": "犀牛",
    "common.camel": "駱駝",
    "common.house": "屋",
    "common.bag": "袋",
    "common.walk": "行",
    "common.run": "跑",
    "common.wheel": "輪",
    "common.jump": "跳",
    "common.word": "詞",
    "common.president_name": "習近平",
    "common.china": "中國",
    "common.spring": "春天",
    "common.summer": "夏天",
    "common.autumn": "秋天",
    "common.winter": "冬天",
    "common.month_1": "一月",
    "common.month_2": "二月",
    "common.month_3": "三月",
    "common.month_4": "四月",
    "common.month_5": "五月",
    "common.month_6": "六月",
    "common.month_7": "七月",
    "common.month_8": "八月",
    "common.month_9": "九月",
    "common.month_10": "十月",
    "common.month_11": "十一月",
    "common.month_12": "十二月",
    "common.day_sunday": "星期日",
    "common.day_monday": "星期一",
    "common.day_tuesday": "星期二",
    "common.day_wednesday": "星期三",
    "common.day_thursday": "星期四",
    "common.day_friday": "星期五",
    "common.day_saturday": "星期六",
  },
  fr: {
    // Language names
    "language.english": "English",
    "language.chinese": "中文",
    "language.cantonese": "廣東話",
    "language.french": "Français",

    // Audio instructions
    "audio.instruction": "🔊 Instruction Audio",
    "audio.instruction_playing": "🔊 Lecture en cours...",
    "audio.instruction_error": "Instruction audio non disponible",
    "audio.error_playing": "Erreur lors de la lecture audio. Veuillez réessayer.",
    "audio.not_supported": "Synthèse vocale non prise en charge dans ce navigateur.",

    // Registration & Login
    "register.title": "S'inscrire avec le numéro de téléphone",
    phone: "Numéro de téléphone",
    "register.submit": "S'inscrire",
    "register.error.invalid": "Veuillez entrer un numéro de téléphone valide",
    "register.error.exists": "Numéro de téléphone déjà enregistré",
    "login.title": "Se connecter avec le numéro de téléphone",
    "login.submit": "Se connecter",
    "login.error.notfound": "Numéro de téléphone introuvable",
    "login.admin": "Connexion administrateur",
    "login.enter_phone": "Entrez votre numéro de téléphone enregistré pour continuer",
    "login.new_user": "Nouvel utilisateur ? S'inscrire ici",
    "login.already_account": "Vous avez déjà un compte ? Connectez-vous ici",
    "registration.description": "Entrez votre numéro de téléphone pour commencer l'évaluation de santé mentale",
    "dummy_pin.label": "PIN fictif",
    "dummy_pin.placeholder.login": "Entrer le PIN fictif",
    "dummy_pin.placeholder.register": "Créer un PIN fictif",

    // Dashboard
    "dashboard.title": "Tableau de bord d'évaluation de santé mentale",
    "dashboard.moca": "Évaluation cognitive de Montréal (MoCA)",
    "dashboard.moca.description": "Évaluation cognitive de Montréal - 30 points au total",
    "dashboard.mmse": "Mini-examen de l'état mental (MMSE)",
    "dashboard.mmse.description": "Mini-examen de l'état mental - 30 points au total",
    "dashboard.upload": "Téléchargement d'images de médecine traditionnelle chinoise (MTC)",
    "dashboard.upload.description": "Télécharger des images médicales et des documents",
    "dashboard.completed": "Terminé",
    "dashboard.pending": "En attente",
    "dashboard.resume": "Reprendre l'évaluation",
    "dashboard.view_results": "Voir les résultats",
    "dashboard.retake": "Réésayer",
    "dashboard.confirm_retake": "Confirmer",
    "dashboard.score": "Score",
    "dashboard.results_final": "Évaluation terminée. Les résultats sont définitifs.",
    "dashboard.manage_files": "Gérer les fichiers",
    "dashboard.upload_files": "Télécharger des fichiers",
    "dashboard.files_uploaded": "Fichiers téléchargés : {count}",
    "dashboard.phone": "Téléphone",
    "dashboard.logout": "Se déconnecter",

    // MoCA
    "moca.title": "Évaluation cognitive de Montréal",
    "moca.visuospatial": "Compétences visuospatiales - Dessin d'horloge",
    "moca.visuospatial.instruction":
      "Faites glisser les aiguilles de l'horloge pour afficher l'heure : 10 après 2 (2h10)",
    "moca.executive": "Fonction exécutive - Test de traçage",
    "moca.executive.instruction":
      "Connectez les cercles dans l'ordre alterné : 1-A-2-B-3-C-4-D. Les cercles 1, A et 2 sont pré-connectés.",
    "moca.naming": "Nommer les animaux",
    "moca.naming.instruction": "Regardez chaque image et tapez le nom de l'animal que vous voyez.",
    "moca.memory": "Tâches de mémoire",
    "moca.memory.instruction": "Vous verrez {count} mots un par un. Souvenez-vous d'eux pour les rappeler plus tard.",
    "moca.attention": "Tâches d'attention",
    "moca.attention.instruction": "Regardez attentivement l'image et comptez le nombre de chiens que vous pouvez voir.",
    "moca.language": "Langage et abstraction",
    "moca.language.instruction": "Écoutez attentivement et complétez les tâches.",
    "moca.orientation": "Orientation",
    "moca.orientation.instruction": "Veuillez répondre aux questions suivantes sur la date et le lieu actuels.",

    // MMSE
    "mmse.title": "Mini-examen de l'état mental",
    "mmse.orientation": "Orientation",
    "mmse.orientation.instruction": "Veuillez répondre aux questions suivantes sur le temps et le lieu.",
    "mmse.registration": "Enregistrement et rappel",
    "mmse.attention": "Attention et calcul",
    "mmse.naming": "Nommer les objets",
    "mmse.naming.instruction": "Regardez chaque image et tapez le nom de l'objet que vous voyez.",
    "mmse.repetition": "Répétition",
    "mmse.repetition.instruction": "Écoutez attentivement la phrase et tapez exactement ce que vous entendez.",
    "mmse.writing": "Écriture",
    "mmse.writing.instruction":
      "Veuillez écrire une phrase complète. La phrase doit avoir un sujet et un verbe et avoir du sens.",
    "mmse.copying": "Copie de design",
    "mmse.copying.instruction": "Regardez la forme ci-dessous et répondez à la question à ce sujet.",

    // Questions
    "question.date": "Quelle est la date d'aujourd'hui ?",
    "question.month": "Quel est le mois actuel ?",
    "question.year": "Quelle est l'année actuelle ?",
    "question.day": "Quel jour de la semaine sommes-nous ?",
    "question.country": "Dans quel pays sommes-nous ?",
    "question.season": "Quelle saison sommes-nous ?",
    "question.president": "Qui est le président actuel ?",
    "question.sea": "Nommez une mer :",
    "question.similarity": "En quoi un train et un vélo se ressemblent-ils ?",
    "question.dogs": "Combien de chiens voyez-vous ?",
    "question.angles": "Combien d'angles cette forme a-t-elle ?",
    "question.subtract": "Combien font 10 moins 7 ?",
    "question.add": "Que devons-nous ajouter à 4 pour obtenir 7 ?",
    "question.your_answer": "Votre réponse :",
    "question.type_sentence": "Tapez la phrase que vous avez entendue :",
    "question.write_sentence": "Écrivez votre phrase ici :",
    "question.animal_label": "Animal {index} :",
    "question.object_label": "Objet {index} :",

    // Audio sentences
    "audio.moca_sentence_en_path": "/audio/moca_sentence_en.mp3",
    "audio.moca_sentence_zh_path": "/audio/moca_sentence_zh.mp3",
    "audio.mmse_sentence_en_path": "/audio/mmse_sentence_en.mp3",
    "audio.mmse_sentence_zh_path": "/audio/mmse_sentence_zh.mp3",
    "audio.play": "Lire l'audio",
    "audio.playing": "Lecture en cours...",
    "audio.played_success": "✓ Audio lu. Maintenant tapez ce que vous avez entendu ci-dessous.",
    "audio.error_playing": "Erreur lors de la lecture audio. Veuillez réessayer.",

    // Memory words
    "memory.moca.words": ["Visage", "Velours", "Église", "Marguerite", "Rouge"],
    "memory.mmse.words": ["Pomme", "Table", "Sou"],
    "memory.get_ready": "Préparez-vous ! Les mots apparaîtront dans {countdown} secondes...",
    "memory.word_of": "Mot {current} sur {total}",
    "memory.preparing_recall": "Préparation de la phase de rappel...",
    "memory.recall_instruction": "Veuillez taper les {count} mots que vous venez de voir, dans n'importe quel ordre.",
    "memory.submit_recall": "Soumettre le rappel",

    // Upload
    "upload.instruction":
      "Téléchargez vos images médicales et documents. Formats pris en charge : PNG, JPEG, PDF (max 10 Mo chacun)",
    "upload.drag_drop": "Déposez les fichiers ici ou cliquez pour parcourir",
    "upload.file_types": "Fichiers PNG, JPEG, PDF jusqu'à 10 Mo chacun",
    "upload.error.invalid_file_type_size":
      "Veuillez sélectionner des fichiers valides (PNG, JPEG, PDF) de moins de 10 Mo",
    "upload.error.failed": "Échec du téléchargement",
    "upload.error.remove_failed": "Échec de la suppression du fichier",
    "upload.uploading": "Téléchargement des fichiers...",
    "upload.uploaded_files": "Fichiers téléchargés ({count})",
    "upload.complete_section": "Terminer la section de téléchargement",
    "upload.using_uploaded_images": "Utilisation de vos images téléchargées pour cette tâche.",

    // Results Display
    "results.title": "Résultats de l'évaluation {assessmentType}",
    "results.score_percentage": "Score de {percentage}%",
    "results.section_breakdown": "Répartition par section",
    "results.points": "{score} points",
    "results.back_to_dashboard": "Retour au tableau de bord",
    "results.interpretation.normal": "Normal",
    "results.interpretation.mild_impairment": "Déficience cognitive légère",
    "results.interpretation.possible_decline": "Déclin cognitif possible",
    "results.interpretation.severe_impairment": "Déficience cognitive sévère",
    "results.moca.normal_range": "26-30 : Cognition normale",
    "results.moca.mild_range": "18-25 : Déficience cognitive légère",
    "results.moca.decline_range": "<18 : Déclin cognitif possible",
    "results.mmse.normal_range": "21-28 : Cognition normale",
    "results.mmse.mild_range": "15-20 : Déficience cognitive légère",
    "results.mmse.severe_range": "<14 : Déficience cognitive sévère",

    // Admin Panel
    "admin.title": "Tableau de bord administrateur",
    "admin.login_title": "Connexion administrateur",
    "admin.username": "Nom d'utilisateur",
    "admin.password": "Mot de passe",
    "admin.login_button": "Se connecter",
    "admin.view_assessments": "Voir les évaluations",
    "admin.view_files": "Voir les fichiers",
    "admin.export_csv": "Exporter CSV",
    "admin.total_users": "Total des utilisateurs",
    "admin.completed_assessments": "Évaluations terminées",
    "admin.avg_moca_score": "Score MoCA moyen",
    "admin.uploaded_files": "Fichiers téléchargés",
    "admin.registered": "Enregistré",
    "admin.assessments_count": "{count} évaluations",
    "admin.files_count": "{count} fichiers",
    "admin.completed_count": "{count} terminées",
    "admin.in_progress_count": "{count} en cours",
    "admin.select_user": "Sélectionnez un utilisateur pour voir ses détails",
    "admin.user_files": "Fichiers utilisateur",
    "admin.assessment_details": "Détails de l'évaluation",
    "admin.no_files_uploaded": "Aucun fichier téléchargé par cet utilisateur",
    "admin.no_completed_assessments": "Aucune évaluation terminée par cet utilisateur",
    "admin.no_progress_assessments": "Aucune évaluation en cours pour cet utilisateur",
    "admin.last_updated": "Dernière mise à jour",
    "admin.current_step": "Étape actuelle",
    "admin.scores_so_far": "Scores jusqu'à présent",
    "admin.total_score": "Score total",
    "admin.section_scores": "Scores par section",
    "admin.laboratory_analysis": "Analyse de laboratoire :",
    "admin.enter_analysis": "Entrer l'analyse de laboratoire...",
    "admin.update_analysis": "Mettre à jour l'analyse",
    "admin.registered_users": "Utilisateurs enregistrés",
    "admin.assessments_in_progress": "Évaluations en cours",
    "admin.avg_scores_title": "Scores d'évaluation moyens",
    "admin.score_distribution_title": "Distribution des scores",
    "admin.progress_trend_title": "Tendances de progression de l'évaluation au fil du temps",
    "admin.select_user_filter": "Sélectionner un utilisateur",
    "admin.all_users": "Tous les utilisateurs",
    "admin.select_assessment_type": "Sélectionner le type d'évaluation",
    "admin.all_assessments": "Toutes les évaluations",

    // Theme
    "theme.light": "Mode clair",
    "theme.dark": "Mode sombre",
    "theme.system": "Système",

    // Common
    "common.assessment": "Évaluation",
    "common.step": "Étape",
    "common.of": "de",
    "common.progress": "Progrès",
    "common.next": "Suivant",
    "common.submit": "Soumettre",
    "common.back": "Retour",
    "common.score": "Score",
    "common.total": "Total",
    "common.loading": "Chargement...",
    "common.login": "Se connecter",
    "common.logout": "Se déconnecter",
    "common.resume": "Reprendre",
    "common.start": "Commencer l'évaluation",
    "common.view_results": "Voir les résultats",
    "common.retake": "Réésayer",
    "common.confirm_retake": "Confirmer",
    "common.skip_task": "Ignorer la tâche",
    "common.animal": "Animal",
    "common.object": "Objet",
    "common.television": "télévision",
    "common.tiger": "tigre",
    "common.rhinoceros": "rhinocéros",
    "common.camel": "chameau",
    "common.house": "maison",
    "common.bag": "sac",
    "common.walk": "marcher",
    "common.run": "courir",
    "common.wheel": "roue",
    "common.jump": "sauter",
    "common.word": "Mot",
    "common.president_name": "xi jinping",
    "common.china": "chine",
    "common.spring": "printemps",
    "common.summer": "été",
    "common.autumn": "automne",
    "common.winter": "hiver",
    "common.month_1": "janvier",
    "common.month_2": "février",
    "common.month_3": "mars",
    "common.month_4": "avril",
    "common.month_5": "mai",
    "common.month_6": "juin",
    "common.month_7": "juillet",
    "common.month_8": "août",
    "common.month_9": "septembre",
    "common.month_10": "octobre",
    "common.month_11": "novembre",
    "common.month_12": "décembre",
    "common.day_sunday": "dimanche",
    "common.day_monday": "lundi",
    "common.day_tuesday": "mardi",
    "common.day_wednesday": "mercredi",
    "common.day_thursday": "jeudi",
    "common.day_friday": "vendredi",
    "common.day_saturday": "samedi",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string, options?: Record<string, any>): string => {
    let text = translations[language][key as keyof (typeof translations)["en"]] || key
    if (options) {
      for (const [optionKey, value] of Object.entries(options)) {
        text = text.replace(`{${optionKey}}`, String(value))
      }
    }
    return text
  }

  const getLanguageName = (lang: Language): string => {
    return t(
      `language.${lang === "en" ? "english" : lang === "zh" ? "chinese" : lang === "yue" ? "cantonese" : "french"}`,
    )
  }

  const getSpeechLanguage = (lang: Language): string => {
    const speechLanguages = {
      en: "en-US",
      zh: "zh-CN",
      yue: "zh-HK", // Cantonese (Hong Kong)
      fr: "fr-FR",
    }
    return speechLanguages[lang]
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getLanguageName, getSpeechLanguage }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export { LanguageContext }
