const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error("Missing Supabase URL or Anon Key environment variables.")
}

// This file is kept for backward compatibility during migration
export { createClient as supabase } from "@/lib/supabase/client"

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string // Changed to string (UUID)
          phone_number: string
          created_at: string
        }
        Insert: {
          id?: string // Allow UUID to be generated by default
          phone_number: string
        }
        Update: {
          phone_number?: string
          created_at?: string
        }
      }
      assessments: {
        Row: {
          id: string
          user_id: string // Changed to string (UUID)
          assessment_type: "MOCA" | "MMSE"
          total_score: number
          section_scores: Record<string, any>
          completed_at: string
          laboratory_analysis?: string
        }
        Insert: {
          user_id: string // Changed to string (UUID)
          assessment_type: "MOCA" | "MMSE"
          total_score: number
          section_scores: Record<string, any>
          laboratory_analysis?: string
        }
        Update: {
          total_score?: number
          section_scores?: Record<string, any>
          laboratory_analysis?: string
        }
      }
      uploaded_files: {
        Row: {
          id: string
          user_id: string // Changed to string (UUID)
          filename: string
          file_path: string
          file_type: string
          file_size: number // Correctly typed here
          uploaded_at: string
        }
        Insert: {
          user_id: string // Changed to string (UUID)
          filename: string
          file_path: string
          file_type: string
          file_size: number // Correctly typed here
        }
      }
      admin_users: {
        Row: {
          id: string
          username: string
          password_hash: string
          created_at: string
        }
      }
      user_progress: {
        Row: {
          id: string // This is the user_id, which is now UUID
          user_id: string // Changed to string (UUID)
          assessment_type: "MOCA" | "MMSE"
          current_step: number
          scores: number[]
          updated_at: string
        }
        Insert: {
          user_id: string // Changed to string (UUID)
          assessment_type: "MOCA" | "MMSE"
          current_step: number
          scores: number[]
        }
        Update: {
          current_step?: number
          scores?: number[]
          updated_at?: string
        }
      }
    }
  }
}
